# fly.toml app configuration file generated for blue-surf-3148 on 2023-10-12T12:11:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blue-surf-3148"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[checks]
  [checks.alive]
   type = "tcp"
   interval = "15s"
   timeout = "2s"
   grace_period = "5s"

  [checks.name_of_your_http_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 5000
    timeout = "10s"
    type = "http"
    [checks.name_of_your_http_check.headers]
      Content-Type = "application/json"
      Authorization = "super-secret"

