# fly.toml app configuration file generated for phoneci on 2023-10-24T14:54:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "phoneci"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
[build.args]
    NODE_VERSION = "16.20.2"

[env]
  PORT = "3001"

[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
